[package]
name = "AgentPayStream"
version = "1.0.0"

[addresses]
agentpay_stream = "0x2c8f0d41b9fb474cfc59378a695eb74d3e4507d7107cad3fe47cea61caaa770d"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.11.0"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.11.0"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.AptosToken]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-node-v1.11.0"
subdir = "aptos-move/framework/aptos-token"

